- name: "Install 'vlc' package"
  ansible.builtin.package:
    name: vlc
    state: present
  become: true
  become_user: root

# NOTE: libdvdnav and libdvdread are installed with main vlc package
#       ...uncertain whether libdvdcss is included with these packages

